package dev.caecorthus.sparkwitch.client.usec;

import java.util.ArrayList;
import java.util.List;

/**
 * Client only, pure: the attachment screen's bolt-action rifle line art, muzzle to the right, 189 x 54 GUI px (local x
 * 0..188, y -5..48), in four variants (muzzle brake or suppressor, magazine fitted or a dashed ghost). Each pixel has a
 * semantic {@link Ink}; {@code UsecAttachmentPaint} picks the colours, so a restyle never touches this data. The rows
 * draw the AXMC with its 1-6x24 LPVO (owner, 2026-10-08: solid AX stock, long forend tube, short optic on a cantilever
 * mount) on the anchors of the owner-approved U2 mockup ({@code UsecAttachmentLayout}); they are generated by
 * {@code usec-art/rifle-axmc-lpvo/ui/rifle_art.py} and run-length encoded as count + ink character ({@code .} =
 * transparent) by {@code emit_java.py} beside it.
 * 仅客户端，纯数据：配件界面的栓动步枪线稿，枪口朝右，189 × 54 GUI 像素（局部 x 0..188，y -5..48），共四种变体（制退器或
 * 消音器、已装弹匣或虚线弹匣）。每个像素带有语义 {@link Ink}，颜色由 {@code UsecAttachmentPaint} 决定，换皮从不触碰这些
 * 数据。各行绘制带 1-6×24 低倍率可变瞄具的 AXMC（所有者 2026-10-08：实心 AX 枪托、长护木管、悬臂座上的短瞄具），沿用所有者
 * 批准的 U2 样稿锚点（{@code UsecAttachmentLayout}）；由 {@code usec-art/rifle-axmc-lpvo/ui/rifle_art.py} 生成，并由同目录的
 * {@code emit_java.py} 按“数量 + 墨水字符”行程编码（{@code .} 为透明）。
 */
public final class UsecAttachmentRifleArt {
    public static final int WIDTH = 189;
    public static final int HEIGHT = 54;
    /** Local y of the first row (headroom above the optic). 第一行的局部 y（瞄具上方的留白）。 */
    public static final int TOP = -5;

    /** Semantic pixel class. 像素语义类别。 */
    public enum Ink {
        BODY_FILL('b'),
        LINE('B'),
        DETAIL('d'),
        MAG_FILL('m'),
        MAG_LINE('M'),
        MUZZLE_FILL('z'),
        MUZZLE_LINE('Z'),
        MAG_GHOST('g');

        private final char code;

        Ink(char code) {
            this.code = code;
        }

        static Ink of(char code) {
            for (Ink ink : values()) {
                if (ink.code == code) {
                    return ink;
                }
            }
            throw new IllegalArgumentException("unknown ink " + code);
        }
    }

    /** One horizontal run at local (x, y). 局部坐标 (x, y) 处的一段水平像素。 */
    public record Run(int x, int y, int length, Ink ink) {
    }

    private UsecAttachmentRifleArt() {
    }

    /** Runs of one variant, top to bottom. 某一变体的像素段，自上而下。 */
    public static List<Run> runs(boolean suppressed, boolean magazine) {
        return Decoded.RUNS[variant(suppressed, magazine)];
    }

    /** Ink at local (x, y), or null when transparent or outside. 局部 (x, y) 处的墨水；透明或越界时为 null。 */
    public static Ink inkAt(boolean suppressed, boolean magazine, int x, int y) {
        int row = y - TOP;
        if (x < 0 || x >= WIDTH || row < 0 || row >= HEIGHT) {
            return null;
        }
        return Decoded.GRIDS[variant(suppressed, magazine)][row][x];
    }

    private static int variant(boolean suppressed, boolean magazine) {
        return (suppressed ? 2 : 0) + (magazine ? 0 : 1);
    }

    /** Decoded on first use, after the data arrays below are initialised. 首次使用时解码，此时下方数据数组已初始化。 */
    private static final class Decoded {
        private static final String[][] VARIANTS = {BRAKE_MAG, BRAKE_NO_MAG, SUPPRESSED_MAG, SUPPRESSED_NO_MAG};
        @SuppressWarnings("unchecked")
        private static final List<Run>[] RUNS = new List[VARIANTS.length];
        private static final Ink[][][] GRIDS = new Ink[VARIANTS.length][][];

        static {
            for (int index = 0; index < VARIANTS.length; index++) {
                RUNS[index] = decode(VARIANTS[index]);
                Ink[][] grid = new Ink[HEIGHT][WIDTH];
                for (Run run : RUNS[index]) {
                    for (int x = run.x(); x < run.x() + run.length(); x++) {
                        grid[run.y() - TOP][x] = run.ink();
                    }
                }
                GRIDS[index] = grid;
            }
        }
    }

    static List<Run> decode(String[] rows) {
        if (rows.length != HEIGHT) {
            throw new IllegalStateException("rifle art must have " + HEIGHT + " rows");
        }
        List<Run> runs = new ArrayList<>();
        for (int row = 0; row < rows.length; row++) {
            String line = rows[row];
            int x = 0;
            int count = 0;
            for (int i = 0; i < line.length(); i++) {
                char c = line.charAt(i);
                if (Character.isDigit(c)) {
                    count = count * 10 + (c - '0');
                    continue;
                }
                if (c != '.') {
                    runs.add(new Run(x, TOP + row, count, Ink.of(c)));
                }
                x += count;
                count = 0;
            }
            if (x != WIDTH) {
                throw new IllegalStateException("rifle art row " + row + " is " + x + " px wide");
            }
        }
        return List.copyOf(runs);
    }

    // ---- generated data (do not edit by hand) / 生成的数据（请勿手改） ----
    static final String[] BRAKE_MAG = {
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "56.2B7.7B117.",
            "47.8B1.2B7.1B1b3d1b1B117.",
            "47.1B1b1d5b1B2b1B1.3B2.1B5b1B2.3B2.9B101.",
            "47.1B1b1d6b2d1b1B1b1d1b2B7b2B1b1d1b2B6b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d1b1B1b1d1b3B2b1d2b3B1b1d1b2B6b1d1b1B101.",
            "5.1B41.1B1b1d5b4B1.1B1b1B3.1B3b1B3.1B1b1B2.9B101.",
            "2.3B1b1B6.22B12.8B4.1B3b3B5b3B2b1B112.",
            "1.1B1d3b1B5.1B22b1B23.1B1b3d3b10B112.",
            "1B1b1d1b1d1b1B5.1B22b1B23.2B2b1B2b1B122.",
            "1B1b1d1b1d1b1B5.5B2b10B2b5B13.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B39.",
            "1B1b1d1b1d1b1B10.2B10.2B11.7B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B38.",
            "1B1b1d1b1d1b1B10.2B10.2B11.1B106b1B39.",
            "1B1b1d1b1d2b10B2b5B3d2B2b11B15b1d41b1d50b1B38.",
            "1B1b1d1b1d18b1d3b1d29b1d16b12d13b1d50b1B29.8Z1.",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d50b1B29.1Z7z1Z",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d4b4d3b4d3b4d3b4d3b4d3b4d3b4d1b29B1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d3b34d1b5d9b1d16b12d13b1d80b1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d80b1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d51b29B1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d5b28d7b1d11b1d41b1d50b1B29.1Z7z1Z",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d41b1d50b1B29.8Z1.",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d65b11B15b1B39.",
            "1B1b1d1b1d5b1d26b1d7b1d3b3B2b8B12b4B1b7B1b1B16M18b1B11.1B1b1B2b1B2b1B2b1B2b1B40.",
            "1B1b1d1b1d5b1d25b2d7b1d2b1B3.2B8.1B10b1B4.1B7.1B1.2M13m1M17B1b1B11.2B1.2B1.2B1.2B1.2B41.",
            "1B1b1d1b1d5b1d23b2d5b8B4.1B8.1B9b2B4.1B7.1B3.1M1m1d9m1M18.2B66.",
            "1B1b1d1b1d5b1d21b2d5b2B10.2B1b2B5.1B9b1B1.1B5.1B6.1B3.1M1m1d9m1M18.2B66.",
            "1B1b1d1b1d5b1d19b2d5b2B11.1B5b1B4.1B9b1B1.1B5.1B6.1B3.1M11m1M86.",
            "1B1b1d1b1d5b1d17b2d6b1B13.1B5b1B4.1B9b1B1.1B5.1B6.1B3.1M11m1M86.",
            "1B1b1d1b1d5b18d6b2B14.1B5b1B4.1B1b5d3b1B1.1B12.1B3.1M11d1M86.",
            "1B1b1d1b1d27b2B16.1B5b1B3.1B10b1B1.1B12.1B3.1M11m1M86.",
            "1B1b1d1b1d25b2B19.5B4.1B10b1B1.13B4.1M11m1M86.",
            "1B1b1d1b1d2b2B17b4B30.1B9b1B19.1M11m1M86.",
            "1B1b1d1b1d1b1B2.17B34.1B1b5d3b1B19.1M11m1M86.",
            "1B1b1d1b1d1b1B52.1B10b1B19.1M11d1M86.",
            "1.1B1d3b1B52.1B10b1B19.1M11m1M86.",
            "2.3B1b1B52.1B10b1B19.1M11m1M86.",
            "5.1B53.1B1b5d4b1B19.1M11m1M86.",
            "58.1B10b1B20.1M11m1M86.",
            "58.1B10b1B20.1M11m1M86.",
            "58.1B10b1B20.1M11m1M86.",
            "59.1B8b2B19.1M13m1M85.",
            "60.8B21.1M13m1M85.",
            "89.15M85."
    };
    static final String[] BRAKE_NO_MAG = {
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "56.2B7.7B117.",
            "47.8B1.2B7.1B1b3d1b1B117.",
            "47.1B1b1d5b1B2b1B1.3B2.1B5b1B2.3B2.9B101.",
            "47.1B1b1d6b2d1b1B1b1d1b2B7b2B1b1d1b2B6b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d1b1B1b1d1b3B2b1d2b3B1b1d1b2B6b1d1b1B101.",
            "5.1B41.1B1b1d5b4B1.1B1b1B3.1B3b1B3.1B1b1B2.9B101.",
            "2.3B1b1B6.22B12.8B4.1B3b3B5b3B2b1B112.",
            "1.1B1d3b1B5.1B22b1B23.1B1b3d3b10B112.",
            "1B1b1d1b1d1b1B5.1B22b1B23.2B2b1B2b1B122.",
            "1B1b1d1b1d1b1B5.5B2b10B2b5B13.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B39.",
            "1B1b1d1b1d1b1B10.2B10.2B11.7B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B38.",
            "1B1b1d1b1d1b1B10.2B10.2B11.1B106b1B39.",
            "1B1b1d1b1d2b10B2b5B3d2B2b11B15b1d41b1d50b1B38.",
            "1B1b1d1b1d18b1d3b1d29b1d16b12d13b1d50b1B29.8Z1.",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d50b1B29.1Z7z1Z",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d4b4d3b4d3b4d3b4d3b4d3b4d3b4d1b29B1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d3b34d1b5d9b1d16b12d13b1d80b1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d80b1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d51b29B1Z1z1d1z1d1z1d1z1Z",
            "1B1b1d1b1d5b28d7b1d11b1d41b1d50b1B29.1Z7z1Z",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d41b1d50b1B29.8Z1.",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d65b11B15b1B39.",
            "1B1b1d1b1d5b1d26b1d7b1d3b3B2b8B12b4B1b7B1b2B2g1B2g1B2g1B2g1b2g19b1B11.1B1b1B2b1B2b1B2b1B2b1B40.",
            "1B1b1d1b1d5b1d25b2d7b1d2b1B3.2B8.1B10b1B4.1B7.1B1.2g9.4B1g17B1b1B11.2B1.2B1.2B1.2B1.2B41.",
            "1B1b1d1b1d5b1d23b2d5b8B4.1B8.1B9b2B4.1B7.1B3.1g11.1g18.2B66.",
            "1B1b1d1b1d5b1d21b2d5b2B10.2B1b2B5.1B9b1B1.1B5.1B6.1B3.1g11.1g18.2B66.",
            "1B1b1d1b1d5b1d19b2d5b2B11.1B5b1B4.1B9b1B1.1B5.1B6.1B102.",
            "1B1b1d1b1d5b1d17b2d6b1B13.1B5b1B4.1B9b1B1.1B5.1B6.1B3.1g11.1g86.",
            "1B1b1d1b1d5b18d6b2B14.1B5b1B4.1B1b5d3b1B1.1B12.1B3.1g11.1g86.",
            "1B1b1d1b1d27b2B16.1B5b1B3.1B10b1B1.1B12.1B102.",
            "1B1b1d1b1d25b2B19.5B4.1B10b1B1.13B4.1g11.1g86.",
            "1B1b1d1b1d2b2B17b4B30.1B9b1B19.1g11.1g86.",
            "1B1b1d1b1d1b1B2.17B34.1B1b5d3b1B118.",
            "1B1b1d1b1d1b1B52.1B10b1B19.1g11.1g86.",
            "1.1B1d3b1B52.1B10b1B19.1g11.1g86.",
            "2.3B1b1B52.1B10b1B118.",
            "5.1B53.1B1b5d4b1B19.1g11.1g86.",
            "58.1B10b1B20.1g11.1g86.",
            "58.1B10b1B119.",
            "58.1B10b1B20.1g11.1g86.",
            "59.1B8b2B19.1g99.",
            "60.8B21.1g13.1g85.",
            "90.2g1.2g1.2g1.2g1.2g85."
    };
    static final String[] SUPPRESSED_MAG = {
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "56.2B7.7B117.",
            "47.8B1.2B7.1B1b3d1b1B117.",
            "47.1B1b1d5b1B2b1B1.3B2.1B5b1B2.3B2.9B101.",
            "47.1B1b1d6b2d1b1B1b1d1b2B7b2B1b1d1b2B6b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d1b1B1b1d1b3B2b1d2b3B1b1d1b2B6b1d1b1B101.",
            "5.1B41.1B1b1d5b4B1.1B1b1B3.1B3b1B3.1B1b1B2.9B101.",
            "2.3B1b1B6.22B12.8B4.1B3b3B5b3B2b1B112.",
            "1.1B1d3b1B5.1B22b1B23.1B1b3d3b10B112.",
            "1B1b1d1b1d1b1B5.1B22b1B23.2B2b1B2b1B122.",
            "1B1b1d1b1d1b1B5.5B2b10B2b5B13.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B39.",
            "1B1b1d1b1d1b1B10.2B10.2B11.7B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B38.",
            "1B1b1d1b1d1b1B10.2B10.2B11.1B106b1B39.",
            "1B1b1d1b1d2b10B2b5B3d2B2b11B15b1d41b1d50b1B16.21Z1.",
            "1B1b1d1b1d18b1d3b1d29b1d16b12d13b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d4b4d3b4d3b4d3b4d3b4d3b4d3b4d1b15B1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d3b34d1b5d9b1d16b12d13b1d66b1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d66b1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d51b15B1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d5b28d7b1d11b1d41b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d41b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d65b11B15b1B17.21Z1.",
            "1B1b1d1b1d5b1d26b1d7b1d3b3B2b8B12b4B1b7B1b1B16M18b1B11.1B1b1B2b1B2b1B2b1B2b1B40.",
            "1B1b1d1b1d5b1d25b2d7b1d2b1B3.2B8.1B10b1B4.1B7.1B1.2M13m1M17B1b1B11.2B1.2B1.2B1.2B1.2B41.",
            "1B1b1d1b1d5b1d23b2d5b8B4.1B8.1B9b2B4.1B7.1B3.1M1m1d9m1M18.2B66.",
            "1B1b1d1b1d5b1d21b2d5b2B10.2B1b2B5.1B9b1B1.1B5.1B6.1B3.1M1m1d9m1M18.2B66.",
            "1B1b1d1b1d5b1d19b2d5b2B11.1B5b1B4.1B9b1B1.1B5.1B6.1B3.1M11m1M86.",
            "1B1b1d1b1d5b1d17b2d6b1B13.1B5b1B4.1B9b1B1.1B5.1B6.1B3.1M11m1M86.",
            "1B1b1d1b1d5b18d6b2B14.1B5b1B4.1B1b5d3b1B1.1B12.1B3.1M11d1M86.",
            "1B1b1d1b1d27b2B16.1B5b1B3.1B10b1B1.1B12.1B3.1M11m1M86.",
            "1B1b1d1b1d25b2B19.5B4.1B10b1B1.13B4.1M11m1M86.",
            "1B1b1d1b1d2b2B17b4B30.1B9b1B19.1M11m1M86.",
            "1B1b1d1b1d1b1B2.17B34.1B1b5d3b1B19.1M11m1M86.",
            "1B1b1d1b1d1b1B52.1B10b1B19.1M11d1M86.",
            "1.1B1d3b1B52.1B10b1B19.1M11m1M86.",
            "2.3B1b1B52.1B10b1B19.1M11m1M86.",
            "5.1B53.1B1b5d4b1B19.1M11m1M86.",
            "58.1B10b1B20.1M11m1M86.",
            "58.1B10b1B20.1M11m1M86.",
            "58.1B10b1B20.1M11m1M86.",
            "59.1B8b2B19.1M13m1M85.",
            "60.8B21.1M13m1M85.",
            "89.15M85."
    };
    static final String[] SUPPRESSED_NO_MAG = {
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "189.",
            "56.2B7.7B117.",
            "47.8B1.2B7.1B1b3d1b1B117.",
            "47.1B1b1d5b1B2b1B1.3B2.1B5b1B2.3B2.9B101.",
            "47.1B1b1d6b2d1b1B1b1d1b2B7b2B1b1d1b2B6b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d3b1d6b1d6b1d9b1d1b1B101.",
            "47.1B1b1d6b2d1b1B1b1d1b3B2b1d2b3B1b1d1b2B6b1d1b1B101.",
            "5.1B41.1B1b1d5b4B1.1B1b1B3.1B3b1B3.1B1b1B2.9B101.",
            "2.3B1b1B6.22B12.8B4.1B3b3B5b3B2b1B112.",
            "1.1B1d3b1B5.1B22b1B23.1B1b3d3b10B112.",
            "1B1b1d1b1d1b1B5.1B22b1B23.2B2b1B2b1B122.",
            "1B1b1d1b1d1b1B5.5B2b10B2b5B13.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B1.2B39.",
            "1B1b1d1b1d1b1B10.2B10.2B11.7B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B2b1B38.",
            "1B1b1d1b1d1b1B10.2B10.2B11.1B106b1B39.",
            "1B1b1d1b1d2b10B2b5B3d2B2b11B15b1d41b1d50b1B16.21Z1.",
            "1B1b1d1b1d18b1d3b1d29b1d16b12d13b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d18b1d3b1d29b1d16b1d10b1d13b1d4b4d3b4d3b4d3b4d3b4d3b4d3b4d1b15B1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d3b34d1b5d9b1d16b12d13b1d66b1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d66b1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d40b1d11b1d41b1d51b15B1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d5b28d7b1d11b1d41b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d41b1d50b1B15.1Z2z1d15z1d2z1Z",
            "1B1b1d1b1d5b1d26b1d7b1d11b1d65b11B15b1B17.21Z1.",
            "1B1b1d1b1d5b1d26b1d7b1d3b3B2b8B12b4B1b7B1b2B2g1B2g1B2g1B2g1b2g19b1B11.1B1b1B2b1B2b1B2b1B2b1B40.",
            "1B1b1d1b1d5b1d25b2d7b1d2b1B3.2B8.1B10b1B4.1B7.1B1.2g9.4B1g17B1b1B11.2B1.2B1.2B1.2B1.2B41.",
            "1B1b1d1b1d5b1d23b2d5b8B4.1B8.1B9b2B4.1B7.1B3.1g11.1g18.2B66.",
            "1B1b1d1b1d5b1d21b2d5b2B10.2B1b2B5.1B9b1B1.1B5.1B6.1B3.1g11.1g18.2B66.",
            "1B1b1d1b1d5b1d19b2d5b2B11.1B5b1B4.1B9b1B1.1B5.1B6.1B102.",
            "1B1b1d1b1d5b1d17b2d6b1B13.1B5b1B4.1B9b1B1.1B5.1B6.1B3.1g11.1g86.",
            "1B1b1d1b1d5b18d6b2B14.1B5b1B4.1B1b5d3b1B1.1B12.1B3.1g11.1g86.",
            "1B1b1d1b1d27b2B16.1B5b1B3.1B10b1B1.1B12.1B102.",
            "1B1b1d1b1d25b2B19.5B4.1B10b1B1.13B4.1g11.1g86.",
            "1B1b1d1b1d2b2B17b4B30.1B9b1B19.1g11.1g86.",
            "1B1b1d1b1d1b1B2.17B34.1B1b5d3b1B118.",
            "1B1b1d1b1d1b1B52.1B10b1B19.1g11.1g86.",
            "1.1B1d3b1B52.1B10b1B19.1g11.1g86.",
            "2.3B1b1B52.1B10b1B118.",
            "5.1B53.1B1b5d4b1B19.1g11.1g86.",
            "58.1B10b1B20.1g11.1g86.",
            "58.1B10b1B119.",
            "58.1B10b1B20.1g11.1g86.",
            "59.1B8b2B19.1g99.",
            "60.8B21.1g13.1g85.",
            "90.2g1.2g1.2g1.2g1.2g85."
    };
}
